<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseDataSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');


        // Seeding table: kategori
        DB::table('kategori')->truncate();
        $data = [
            [
                'id' => 1,
                'judul' => 'Informasi Terkini',
                'created_at' => '2025-11-12 23:35:50',
                'updated_at' => '2025-11-12 23:35:50',
            ],
            [
                'id' => 2,
                'judul' => 'Galery Sekolah',
                'created_at' => '2025-11-12 23:35:50',
                'updated_at' => '2025-11-12 23:35:50',
            ],
            [
                'id' => 3,
                'judul' => 'Agenda Sekolah',
                'created_at' => '2025-11-12 23:35:50',
                'updated_at' => '2025-11-12 23:35:50',
            ],
            [
                'id' => 4,
                'judul' => 'Event Sekolah',
                'created_at' => '2025-11-13 00:18:38',
                'updated_at' => '2025-11-13 00:18:38',
            ],
        ];
        DB::table('kategori')->insert($data);


        // Seeding table: petugas
        DB::table('petugas')->truncate();
        $data = [
            [
                'id' => 1,
                'username' => 'admin',
                'email' => 'adminK4@gmail.com',
                'password' => '$2y$12$qO4.FK8IUlfYXHEONGv5rutfjBb0loqZk6yzs2qisNtX42/m7mTqq',
                'remember_token' => 'xvNauBOGI8UcyCIXLQtmoggR0JW12ItmVaMheHcVZr7cF9bnoJGo40jApMGT',
                'created_at' => '2025-11-12 23:35:51',
                'updated_at' => '2025-11-14 17:18:20',
            ],
            [
                'id' => 2,
                'username' => 'staf',
                'email' => 'sitiyuyur@gmail.com',
                'password' => '$2y$12$jMGtO7vpk8x3KdZjOZBPcelrJzjk5GliEeWiqLu4ddThAsQDAP13K',
                'remember_token' => 'ixTqXOCnMuLjnpSFHgyqkysZMPdmNkTrz8fByysjxIjG9WiAn8caspStBjWP',
                'created_at' => '2025-11-12 23:35:51',
                'updated_at' => '2025-11-14 18:20:08',
            ],
            [
                'id' => 5,
                'username' => 'staff',
                'email' => 'sipitsipit@gmail.com',
                'password' => '$2y$12$6o4bX/vyR.Ca6oB8rjTo4.0D0kfzQ9ImJHViue.8DKhyhqvk/K//a',
                'remember_token' => 'iEUtw8fX34JoPyge5y7VgqeEzpBTNMd2BiRHxIAOghd0fxKXUtJ7k9zmqu5L',
                'created_at' => '2025-11-14 18:17:11',
                'updated_at' => '2025-11-14 18:17:11',
            ],
        ];
        DB::table('petugas')->insert($data);


        // Seeding table: users
        DB::table('users')->truncate();
        $data = [
            [
                'id' => 1,
                'name' => 'Test User',
                'email' => 'test@example.com',
                'email_verified_at' => '2025-11-12 23:35:49',
                'password' => '$2y$12$ZejFN7Nu5vE9chEQA.MWDeGce0mw8O2BTh0DLu1.oa7tDaPjrZcAi',
                'remember_token' => 'tRvz148GR9',
                'created_at' => '2025-11-12 23:35:50',
                'updated_at' => '2025-11-12 23:35:50',
            ],
            [
                'id' => 2,
                'name' => 'Administrator',
                'email' => 'admin@galeri-edu.com',
                'email_verified_at' => null,
                'password' => '$2y$12$rW0YDdTZqH9Br4de75FEOONLRiQ/A8fkFGi7jzorIan19eJYRL5AG',
                'remember_token' => 'bU3Keql3GPHjapeArWFXzwgQuV24PBzcJkwmPMCXangqgFMhKuU6rndySqct',
                'created_at' => '2025-11-12 23:35:52',
                'updated_at' => '2025-11-12 23:35:52',
            ],
            [
                'id' => 3,
                'name' => 'Siti Nuraeni',
                'email' => 'siti@galeri-edu.com',
                'email_verified_at' => null,
                'password' => '$2y$12$FyGcUmGP3RUHjCyknG7ApeCDFfgYZxDomLCh03gXkLMUBSKfhbMle',
                'remember_token' => null,
                'created_at' => '2025-11-12 23:35:53',
                'updated_at' => '2025-11-12 23:35:53',
            ],
            [
                'id' => 4,
                'name' => 'Kepala Sekolah',
                'email' => 'kepsek@galeri-edu.com',
                'email_verified_at' => null,
                'password' => '$2y$12$wFN0APH3I1UldBLcRvd4neBZlilU2TcfCTAvG/TzVD2IkZKgrFH3G',
                'remember_token' => null,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 6,
                'name' => 'siti nuraeni',
                'email' => 'sitinuraenst7@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$MpQECY8/b7keRgdgC/Af.uglzOG6EpLqTIsBMWchszPwpVhgOEmK2',
                'remember_token' => 'tX4FmuwL4QKfe8CwZfZJhHdF44jAiVysMrbxFwFz9ioQiQH2Rtm734nFHLMR',
                'created_at' => '2025-11-14 16:46:44',
                'updated_at' => '2025-11-14 16:46:44',
            ],
            [
                'id' => 7,
                'name' => 'YUNISA',
                'email' => 'YUYUNINISA@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$iulJC2JKQfNSMMGVQ2bZKueFCej7JOrCu/GTk4uIPDR4AHeCHDrKq',
                'remember_token' => null,
                'created_at' => '2025-11-14 22:15:22',
                'updated_at' => '2025-11-14 22:15:22',
            ],
        ];
        DB::table('users')->insert($data);


        // Seeding table: posts
        DB::table('posts')->truncate();
        $data = [
            [
                'id' => 1,
                'judul' => 'Perlombaan Teknik Pengelasan',
                'kategori_id' => 3,
                'petugas_id' => 2,
                'isi' => 'Proses pengelasan dalam ajang lomba teknik pengelasan dan fabrikasi logam — momen di mana keahlian dan presisi diuji dalam setiap sambungan logam.',
                'status' => 'published',
                'created_at' => '2025-11-12 23:58:01',
                'updated_at' => '2025-11-13 00:18:22',
            ],
            [
                'id' => 2,
                'judul' => 'Perlombaan Teknik Pengelasan',
                'kategori_id' => 3,
                'petugas_id' => 2,
                'isi' => 'Seorang siswi peserta lomba sedang fokus mengerjakan proses pengelasan pada proyek fabrikasi logam. Ketelitian, ketekunan, dan keterampilan menjadi kunci utama dalam menghasilkan sambungan logam yang sempurna.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:05:10',
                'updated_at' => '2025-11-13 00:18:11',
            ],
            [
                'id' => 3,
                'judul' => 'Serah Terima Jabatan OSIS 2024/2025',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Dari yang lama untuk yang baru, dari pengalaman menuju harapan.
Serah terima jabatan OSIS 2024/2025 — satu semangat, satu tujuan.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:07:16',
                'updated_at' => '2025-11-13 00:07:16',
            ],
            [
                'id' => 5,
                'judul' => 'Serah Terima Jabatan OSIS 2024/2025',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Setiap kepemimpinan meninggalkan jejak, dan setiap generasi melanjutkan langkah.
Selamat bertugas untuk pengurus OSIS 2024/2025. Teruskan semangat dan perjuangan dengan hati yang tulus.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:09:56',
                'updated_at' => '2025-11-13 00:09:56',
            ],
            [
                'id' => 6,
                'judul' => 'Serah Terima Jabatan OSIS 2024/2025',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Tongkat estafet kepemimpinan berpindah tangan bukan akhir, tapi awal dari babak baru perjalanan OSIS menuju masa depan yang lebih gemilang.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:11:25',
                'updated_at' => '2025-11-13 00:11:25',
            ],
            [
                'id' => 7,
                'judul' => 'Serah Terima Jabatan OSIS 2024/2025',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Foto bersama setelah pelaksanaan serah terima jabatan OSIS masa bakti 2024/2025-2025/2026. Momen kebersamaan yang menandai berakhirnya satu periode kepemimpinan dan dimulainya perjalanan baru penuh semangat dan tanggung jawab.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:13:09',
                'updated_at' => '2025-11-13 00:13:09',
            ],
            [
                'id' => 8,
                'judul' => 'Pembangunan Gedung Baru',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Membangun bukan hanya tentang tembok, tapi tentang masa depan.
Sebuah langkah menuju sekolah yang lebih baik.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:14:51',
                'updated_at' => '2025-11-13 00:14:51',
            ],
            [
                'id' => 9,
                'judul' => 'Pembangunan Gedung Baru',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Di bawah teriknya matahari, mereka menanam harapan di setiap bata yang tersusun.
Gedung ini bukan sekadar bangunan, tapi tempat lahirnya mimpi dan masa depan.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:15:42',
                'updated_at' => '2025-11-13 00:15:42',
            ],
            [
                'id' => 10,
                'judul' => 'Pembangunan Gedung Baru',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Dengan keringat dan ketekunan, mereka membangun ruang untuk generasi yang akan datang.
Setiap adukan semen, setiap tiang berdiri adalah wujud nyata dari dedikasi dan harapan.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:16:51',
                'updated_at' => '2025-11-13 00:16:51',
            ],
            [
                'id' => 11,
                'judul' => 'Perlombaan 17 Agustus',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Tawa, semangat, dan warna merah putih memenuhi halaman sekolah.
Bukan sekadar lomba, tapi wujud cinta terhadap tanah air dalam keceriaan yang sederhana.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:18:00',
                'updated_at' => '2025-11-13 00:18:00',
            ],
            [
                'id' => 12,
                'judul' => 'Perlombaan 17 Agustus',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Di setiap sorak dan langkah, ada semangat juang yang tak pernah padam.
Lomba 17 Agustus mengingatkan kita bahwa merdeka bukan hanya tentang masa lalu, tapi juga semangat untuk terus maju.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:20:09',
                'updated_at' => '2025-11-13 00:20:09',
            ],
            [
                'id' => 13,
                'judul' => 'Perlombaan 17 Agustus',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Kegiatan lomba dalam rangka memperingati Hari Kemerdekaan Republik Indonesia ke-80. Melalui semangat kebersamaan dan sportivitas, siswa-siswi berpartisipasi dengan antusias dalam berbagai perlombaan untuk menumbuhkan rasa nasionalisme dan persatuan.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:21:17',
                'updated_at' => '2025-11-13 00:21:17',
            ],
            [
                'id' => 14,
                'judul' => 'Gladi Bersih Trans4crab',
                'kategori_id' => 4,
                'petugas_id' => 2,
                'isi' => 'Setiap langkah, setiap gerak, dan setiap detail dipersiapkan dengan penuh hati.
Gladi bersih TRANS4CRAB tempat di mana kerja keras bertemu dengan harapan.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:23:37',
                'updated_at' => '2025-11-13 00:23:37',
            ],
            [
                'id' => 15,
                'judul' => 'Penampialn siswa/i saat Trans4crab',
                'kategori_id' => 4,
                'petugas_id' => 2,
                'isi' => 'Penampilan peserta dalam acara TRANS4CRAB berlangsung meriah dan penuh antusiasme. Setiap peserta menunjukkan kreativitas, kepercayaan diri, serta kerja sama tim yang luar biasa dalam menampilkan karya terbaiknya.',
                'status' => 'published',
                'created_at' => '2025-11-13 00:24:34',
                'updated_at' => '2025-11-13 00:24:34',
            ],
            [
                'id' => 16,
                'judul' => 'Pengibaran Sang Saka Merah Putih',
                'kategori_id' => 2,
                'petugas_id' => 2,
                'isi' => 'Tiga serangkai Paskibra berdiri tegak, memanggul kehormatan di pundak. Dalam balutan seragam putih yang bersih, mereka fokus menjalankan tugas mulia, mengibarkan Sang Saka Merah Putih. Setiap gerakan adalah janji, setiap tarikan tali adalah penghormatan tertinggi kepada bangsa.',
                'status' => 'published',
                'created_at' => '2025-11-14 11:09:58',
                'updated_at' => '2025-11-14 11:09:58',
            ],
        ];
        DB::table('posts')->insert($data);


        // Seeding table: galery
        DB::table('galery')->truncate();
        $data = [
            [
                'id' => 1,
                'post_id' => 1,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 2,
                'post_id' => 2,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 3,
                'post_id' => 3,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 5,
                'post_id' => 5,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 6,
                'post_id' => 6,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 7,
                'post_id' => 7,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 8,
                'post_id' => 8,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 9,
                'post_id' => 9,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 10,
                'post_id' => 10,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 11,
                'post_id' => 11,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 12,
                'post_id' => 12,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 13,
                'post_id' => 13,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 14,
                'post_id' => 14,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 15,
                'post_id' => 15,
                'position' => null,
                'status' => 'aktif',
            ],
            [
                'id' => 16,
                'post_id' => 16,
                'position' => null,
                'status' => 'aktif',
            ],
        ];
        DB::table('galery')->insert($data);


        // Seeding table: foto
        DB::table('foto')->truncate();
        $data = [
            [
                'id' => 1,
                'galery_id' => 1,
                'file' => '1762991881_0.jpeg',
                'likes' => 0,
                'dislikes' => 1,
                'created_at' => '2025-11-12 23:58:01',
                'updated_at' => '2025-11-15 01:00:01',
            ],
            [
                'id' => 2,
                'galery_id' => 2,
                'file' => '1762992310_0.jpeg',
                'likes' => 1,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:05:10',
                'updated_at' => '2025-11-15 01:00:04',
            ],
            [
                'id' => 3,
                'galery_id' => 3,
                'file' => '1762992436_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:07:16',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 5,
                'galery_id' => 5,
                'file' => '1762992596_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:09:56',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 6,
                'galery_id' => 6,
                'file' => '1762992685_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:11:25',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 7,
                'galery_id' => 7,
                'file' => '1762992789_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:13:09',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 8,
                'galery_id' => 8,
                'file' => '1762992891_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:14:51',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 9,
                'galery_id' => 9,
                'file' => '1762992942_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:15:42',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 10,
                'galery_id' => 10,
                'file' => '1762993011_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:16:51',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 11,
                'galery_id' => 11,
                'file' => '1762993080_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:18:00',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 12,
                'galery_id' => 12,
                'file' => '1762993209_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:20:09',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 13,
                'galery_id' => 13,
                'file' => '1762993277_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:21:17',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 14,
                'galery_id' => 14,
                'file' => '1762993417_0.jpg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:23:37',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 15,
                'galery_id' => 15,
                'file' => '1762993474_0.jpeg',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-13 00:24:34',
                'updated_at' => '2025-11-15 00:59:23',
            ],
            [
                'id' => 16,
                'galery_id' => 16,
                'file' => '1763118598_0.png',
                'likes' => 0,
                'dislikes' => 0,
                'created_at' => '2025-11-14 11:09:58',
                'updated_at' => '2025-11-15 00:59:23',
            ],
        ];
        DB::table('foto')->insert($data);


        // Seeding table: agenda
        DB::table('agenda')->truncate();
        $data = [
            [
                'id' => 1,
                'title' => 'UKK (Uji Kompetensi Keahlian)',
                'description' => 'Ujian Kompetensi Keahlian (UKK) merupakan kegiatan evaluasi akhir bagi siswa kelas XII untuk mengukur pencapaian kompetensi sesuai bidang keahliannya. Melalui UKK, diharapkan siswa mampu menunjukkan kemampuan profesional dan siap menghadapi dunia kerja.',
                'date_label' => 'Rabu-Jumat',
                'time' => '07.00-Selesai',
                'event_date' => '2025-11-19',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 02:47:04',
                'updated_at' => '2025-11-13 02:47:04',
            ],
            [
                'id' => 2,
                'title' => 'UKK (Uji Kompetensi Keahlian) dari Perusahaan',
                'description' => 'Pelaksanaan Ujian Kompetensi Keahlian (UKK) oleh pihak perusahaan menjadi bentuk nyata kerja sama antara sekolah dan dunia industri. Kegiatan ini bertujuan untuk menilai kesiapan siswa dalam menerapkan keahlian sesuai standar kerja profesional di lapangan.',
                'date_label' => 'Senin-Rabu',
                'time' => '07.00-Selesai',
                'event_date' => '2025-11-24',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 02:49:22',
                'updated_at' => '2025-11-13 02:49:22',
            ],
            [
                'id' => 3,
                'title' => 'Tes Pemeriksaan Kesehatan',
                'description' => 'Kegiatan pemeriksaan kesehatan bagi siswa dilaksanakan sebagai upaya menjaga dan memantau kondisi kesehatan peserta didik. Melalui kegiatan ini, sekolah berkomitmen untuk menciptakan lingkungan belajar yang sehat dan nyaman.',
                'date_label' => 'Kamis-Jumat',
                'time' => '08.00-16.00',
                'event_date' => '2025-11-12',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 02:51:39',
                'updated_at' => '2025-11-13 02:51:39',
            ],
            [
                'id' => 4,
                'title' => 'Perekaman E-KTP',
                'description' => 'Kegiatan perekaman e-KTP di sekolah dilaksanakan bekerja sama dengan Dinas Kependudukan dan Pencatatan Sipil (Disdukcapil). Program ini mempermudah siswa yang telah memenuhi syarat usia untuk melakukan perekaman data kependudukan tanpa harus datang ke kantor dinas.',
                'date_label' => 'Senin',
                'time' => '08.00-15.00',
                'event_date' => '2025-11-10',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 02:53:51',
                'updated_at' => '2025-11-13 02:53:51',
            ],
            [
                'id' => 5,
                'title' => 'Sosialisasi PTN, PTS, SNPMB',
                'description' => 'Kegiatan sosialisasi PTN, PTS, dan SNPMB dilaksanakan untuk memberikan informasi dan arahan kepada siswa kelas XII mengenai jalur dan prosedur masuk perguruan tinggi. Melalui kegiatan ini, diharapkan siswa lebih siap dalam menentukan pilihan dan melanjutkan pendidikan ke jenjang yang lebih tinggi.',
                'date_label' => 'Jumat',
                'time' => '07.30-11.00',
                'event_date' => '2025-11-07',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 02:56:36',
                'updated_at' => '2025-11-13 02:56:36',
            ],
            [
                'id' => 6,
                'title' => 'Sosialisasi Ujikom dan PKL',
                'description' => 'Kegiatan sosialisasi Ujikom dan PKL dilaksanakan untuk memberikan pemahaman kepada siswa mengenai pelaksanaan Ujian Kompetensi dan Praktik Kerja Lapangan. Melalui kegiatan ini, siswa dibekali informasi penting terkait persiapan, pelaksanaan, dan penilaian agar dapat mengikuti kegiatan dengan baik dan maksimal.',
                'date_label' => 'Jumat',
                'time' => '07.30-11.00',
                'event_date' => '2025-11-07',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 02:58:06',
                'updated_at' => '2025-11-13 02:58:06',
            ],
            [
                'id' => 7,
                'title' => 'Verifikasi Data Persiapan E-Ijazah',
                'description' => 'Kegiatan verifikasi data persiapan E-Ijazah dilaksanakan untuk memastikan keakuratan identitas dan data akademik siswa sebelum proses penerbitan ijazah elektronik. Langkah ini bertujuan agar seluruh data yang tercantum pada E-Ijazah sesuai dan valid berdasarkan arsip sekolah.',
                'date_label' => 'Selasa',
                'time' => '10.00-13.00',
                'event_date' => '2025-11-04',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-13 03:00:15',
                'updated_at' => '2025-11-13 03:00:15',
            ],
            [
                'id' => 8,
                'title' => 'Kegiatan Pemeiksaan Kesehatan yang Dilakukan oleh Puskesmas Lawang Gintung.',
                'description' => 'Kegiatan pemeriksaan kesehatan oleh Puskesmas Lawang Gintung bertujuan untuk memantau kondisi kesehatan siswa secara berkala. Pemeriksaan meliputi pengukuran tinggi badan, berat badan, kebersihan gigi, indera, serta deteksi dini potensi masalah kesehatan. Melalui kegiatan ini, sekolah berharap dapat meningkatkan kesadaran siswa mengenai pentingnya menjaga kesehatan sejak dini.',
                'date_label' => 'Jumat',
                'time' => '10.00-12.00',
                'event_date' => '2025-11-14',
                'status' => 'aktif',
                'order' => 1,
                'created_at' => '2025-11-14 13:14:41',
                'updated_at' => '2025-11-14 13:14:41',
            ],
            [
                'id' => 9,
                'title' => 'Training of Trainer (ToT) Kesehatan Remaja Berbasis Sekolah',
                'description' => 'Kegiatan Training of Trainer (ToT) Kesehatan Remaja Berbasis Sekolah bertujuan membekali para peserta dengan pengetahuan dan keterampilan mengenai kesehatan remaja. Melalui pelatihan ini, sekolah berharap dapat menciptakan kader-kader muda yang mampu menjadi agen edukasi kesehatan di lingkungan sekolah.',
                'date_label' => 'Rabu',
                'time' => '07.30-10.00',
                'event_date' => '2025-11-12',
                'status' => 'aktif',
                'order' => 0,
                'created_at' => '2025-11-14 13:26:07',
                'updated_at' => '2025-11-14 13:26:07',
            ],
            [
                'id' => 10,
                'title' => 'Kegiatan Pencegahan HIV/AIDS',
                'description' => 'Agenda Pencegahan HIV/AIDS berfokus pada pemberian edukasi mengenai cara penularan, pencegahan, dan fakta ilmiah tentang HIV/AIDS. Kegiatan ini membantu siswa memahami pentingnya perilaku hidup sehat, menjaga diri, serta menghindari tindakan berisiko. Penyuluhan dilakukan secara interaktif agar siswa dapat bertanya dan berdiskusi dengan nyaman.',
                'date_label' => 'Senin',
                'time' => '08.00-11.00',
                'event_date' => '2025-11-10',
                'status' => 'aktif',
                'order' => 2,
                'created_at' => '2025-11-14 13:31:17',
                'updated_at' => '2025-11-14 13:31:17',
            ],
            [
                'id' => 11,
                'title' => 'Simulasi TKA (Tes Kemampuan Akademik)',
                'description' => 'Kegiatan Simulasi TKA (Tes Kemampuan Akademik) dilaksanakan untuk melatih siswa dalam memahami bentuk soal, tingkat kesulitan, serta strategi pengerjaan TKA. Melalui simulasi ini, siswa diharapkan lebih siap menghadapi ujian sebenarnya dengan percaya diri dan kemampuan yang optimal.',
                'date_label' => 'Senin',
                'time' => '07.30-10.00',
                'event_date' => '2025-10-27',
                'status' => 'aktif',
                'order' => 3,
                'created_at' => '2025-11-14 13:41:12',
                'updated_at' => '2025-11-14 13:41:12',
            ],
            [
                'id' => 12,
                'title' => 'Workshop Rutin SMKN 4 Bogor',
                'description' => 'Kegiatan Workshop Rutin SMKN 4 Bogor dilaksanakan sebagai upaya meningkatkan kompetensi dan keterampilan peserta didik sesuai dengan bidang keahlian masing-masing. Melalui workshop ini, siswa mendapatkan pengalaman praktik yang mendukung kesiapan mereka dalam dunia kerja maupun pendidikan lanjutan.',
                'date_label' => 'Senin',
                'time' => '07.30-09.00',
                'event_date' => '2025-11-10',
                'status' => 'aktif',
                'order' => 4,
                'created_at' => '2025-11-14 13:44:26',
                'updated_at' => '2025-11-14 13:44:26',
            ],
        ];
        DB::table('agenda')->insert($data);


        // Seeding table: informasi
        DB::table('informasi')->truncate();
        $data = [
            [
                'id' => 2,
                'title' => 'Pembangunan Masjid Riyadus  Shalihin',
                'description' => 'Infaq pembangunan Masjid Riyadus Shalihin pada 10 November terkumpul dari siswa sebesar:
👥 Siswa: Rp 817.200,-  
👨‍🏫 Guru TP: Rp 300.000,-  
📊 Total infaq s.d. hari itu: Rp 33.514.300,-  
📉 Total pengeluaran: Rp 29.797.000,-  
💼 Saldo akhir: Rp 3.717.300,-',
                'icon' => 'fas fa-mosque',
                'date' => '2025-11-10',
                'status' => 'aktif',
                'order' => 1,
                'created_at' => '2025-11-14 22:57:06',
                'updated_at' => '2025-11-14 22:57:06',
            ],
            [
                'id' => 3,
                'title' => 'Pembangunan Masjid Riyadus Shalihin',
                'description' => 'Infaq pembangunan Masjid Riyadus Shalihin pada 11 November terkumpul dari siswa sebesar:
👥 Siswa: Rp 796.500,-  
📊 Total infaq s.d. hari itu: Rp 34.310.800,-  
📉 Pengeluaran tetap: Rp 29.797.000,-  
💼 Saldo akhir: Rp 4.513.800,-',
                'icon' => 'fas fa-mosque',
                'date' => '2025-11-11',
                'status' => 'aktif',
                'order' => 2,
                'created_at' => '2025-11-14 22:59:25',
                'updated_at' => '2025-11-14 22:59:25',
            ],
            [
                'id' => 4,
                'title' => 'Pembangunan Masjid Ruyadus Shalihin',
                'description' => 'Infaq pembangunan Masjid Riyadus Shalihin pada 11 November berasal dari siswa sebesar:
👥 Siswa : Rp 728.500,-  
📊 Total infaq s.d. hari ini: Rp 35.039.300,-  
📉 Pengeluaran tetap: Rp 29.797.000,-  
💼 Saldo akhir: Rp 5.242.300,-',
                'icon' => 'fas fa-mosque',
                'date' => '2025-11-12',
                'status' => 'aktif',
                'order' => 3,
                'created_at' => '2025-11-14 23:01:09',
                'updated_at' => '2025-11-14 23:01:09',
            ],
            [
                'id' => 5,
                'title' => 'Perekaman E-KTP',
                'description' => 'Kegiatan Perekaman E-KTP dilaksanakan di ruang samsung untuk memfasilitasi siswa dalam proses pembuatan identitas kependudukan sehingga lebih mudah, cepat, dan terdata secara resmi.',
                'icon' => 'fas fa-id-card',
                'date' => '2025-11-10',
                'status' => 'aktif',
                'order' => 4,
                'created_at' => '2025-11-14 23:05:01',
                'updated_at' => '2025-11-14 23:05:01',
            ],
            [
                'id' => 6,
                'title' => 'TKA (Tes Kemampuan Akademik)',
                'description' => 'Kegiatan TKA (Tes Kemampuan Akademik) dilaksanakan untuk mengukur kemampuan kognitif siswa melalui soal-soal yang menguji penalaran, logika, dan pemahaman dasar. Tes ini dibagi berdasarkan jurusan dan hari, dengan jadwal serta ruangan sebagai berikut:

Hari Senin-Selasa
Jurusan: PPLG dan TPFL
Ruang: Lab 1 PPLG (untuk PPLG), Lab 1 TJKT (untuk TPFL)
Sesi:
Pagi: 07.30 – 10.00
Siang: 10.30 – 13.00
Sore: 13.30 – 16.00',
                'icon' => 'fas fa-brain',
                'date' => '2025-11-03',
                'status' => 'aktif',
                'order' => 5,
                'created_at' => '2025-11-14 23:17:53',
                'updated_at' => '2025-11-14 23:17:53',
            ],
            [
                'id' => 7,
                'title' => 'TKA (Tes Kemampuan Akademik)',
                'description' => 'Kegiatan TKA (Tes Kemampuan Akademik) dilaksanakan untuk mengukur kemampuan kognitif siswa melalui soal-soal yang menguji penalaran, logika, dan pemahaman dasar. Tes ini dibagi berdasarkan jurusan dan hari, dengan jadwal serta ruangan sebagai berikut:
Hari Rabu-Kamis
Jurusan: TJKT dan TO
Ruang: Lab 1 PPLG (untuk TJKT), Lab TJKT TO (untuk TO)
Sesi:
Pagi: 07.30 – 10.00
Siang: 10.30 – 13.00
Sore: 13.30 – 16.00',
                'icon' => 'fas fa-brain',
                'date' => '2025-11-05',
                'status' => 'aktif',
                'order' => 6,
                'created_at' => '2025-11-14 23:19:40',
                'updated_at' => '2025-11-14 23:19:40',
            ],
        ];
        DB::table('informasi')->insert($data);


        // Seeding table: site_settings
        DB::table('site_settings')->truncate();
        $data = [
            [
                'id' => 1,
                'key' => 'home_hero_title',
                'label' => 'Judul Utama Beranda',
                'type' => 'text',
                'value' => 'Selamat Datang di SMKN 4 BOGOR',
                'group' => 'home',
                'description' => 'Judul utama yang ditampilkan di bagian hero/header halaman beranda',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 2,
                'key' => 'home_hero_subtitle',
                'label' => 'Subjudul Beranda',
                'type' => 'textarea',
                'value' => 'Sekolah Menengah Kejuruan Negeri 4 Bogor siap mencetak generasi yang berkarakter, berkompeten, dan berdaya saing global.',
                'group' => 'home',
                'description' => 'Teks subjudul di bawah judul utama',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 3,
                'key' => 'home_hero_image',
                'label' => 'Gambar Hero Beranda',
                'type' => 'image',
                'value' => '',
                'group' => 'home',
                'description' => 'Gambar latar belakang untuk bagian hero/header',
                'order' => 3,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 4,
                'key' => 'profile_title',
                'label' => 'Judul Halaman Profil',
                'type' => 'text',
                'value' => 'Profil SMKN 4 BOGOR',
                'group' => 'profile',
                'description' => 'Judul halaman profil',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 5,
                'key' => 'profile_content',
                'label' => 'Konten Profil',
                'type' => 'editor',
                'value' => '<p>SMK Negeri 4 Bogor adalah salah satu Sekolah Menengah Kejuruan Negeri yang terletak di Kota Bogor, Jawa Barat. Sekolah ini berdiri sejak tahun 1985 dan telah meluluskan ribuan siswa yang siap bekerja di dunia industri.</p><p>Dengan fasilitas yang lengkap dan tenaga pengajar yang profesional, SMKN 4 Bogor siap mencetak lulusan yang kompeten di bidangnya masing-masing.</p>',
                'group' => 'profile',
                'description' => 'Konten lengkap halaman profil',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 14:31:32',
            ],
            [
                'id' => 6,
                'key' => 'profile_image',
                'label' => 'Gambar Profil',
                'type' => 'image',
                'value' => '',
                'group' => 'profile',
                'description' => 'Gambar untuk halaman profil',
                'order' => 3,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 7,
                'key' => 'vision_title',
                'label' => 'Judul Visi',
                'type' => 'text',
                'value' => 'Visi',
                'group' => 'vision_mission',
                'description' => 'Judul bagian visi',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 8,
                'key' => 'vision_content',
                'label' => 'Isi Visi',
                'type' => 'textarea',
                'value' => 'Menjadi lembaga pendidikan kejuruan yang unggul, berkarakter, dan berdaya saing global pada tahun 2025.',
                'group' => 'vision_mission',
                'description' => 'Teks visi sekolah',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 9,
                'key' => 'mission_title',
                'label' => 'Judul Misi',
                'type' => 'text',
                'value' => 'Misi',
                'group' => 'vision_mission',
                'description' => 'Judul bagian misi',
                'order' => 3,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 10,
                'key' => 'mission_content',
                'label' => 'Isi Misi',
                'type' => 'editor',
                'value' => '<ol><li>Menyelenggarakan pendidikan dan pelatihan yang berkualitas sesuai dengan standar nasional dan internasional</li><li>Mengembangkan kurikulum berbasis kompetensi yang sesuai dengan kebutuhan dunia kerja</li><li>Meningkatkan kualitas tenaga pendidik dan kependidikan secara berkelanjutan</li><li>Menyediakan sarana dan prasarana pendidikan yang memadai dan relevan</li><li>Menjalin kerjasama dengan dunia usaha dan industri dalam rangka peningkatan mutu lulusan</li></ol>',
                'group' => 'vision_mission',
                'description' => 'Teks misi sekolah dalam format list',
                'order' => 4,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 11,
                'key' => 'contact_title',
                'label' => 'Judul Halaman Kontak',
                'type' => 'text',
                'value' => 'Hubungi Kami',
                'group' => 'contact',
                'description' => 'Judul halaman kontak',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 12,
                'key' => 'contact_address',
                'label' => 'Alamat',
                'type' => 'textarea',
                'value' => 'Jl. Raya Tajur, Kp. Buntar RT.02/RW.08, Kel. Muara sari, Kec. Bogor Selatan, RT.03/RW.08, Muarasari, Kec. Bogor Sel., Kota Bogor, Jawa Barat 16137',
                'group' => 'contact',
                'description' => 'Alamat lengkap sekolah',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 15:55:55',
            ],
            [
                'id' => 13,
                'key' => 'contact_phone',
                'label' => 'Telepon',
                'type' => 'text',
                'value' => '(0251) 7547381',
                'group' => 'contact',
                'description' => 'Nomor telepon sekolah',
                'order' => 3,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 15:55:55',
            ],
            [
                'id' => 14,
                'key' => 'contact_email',
                'label' => 'Email',
                'type' => 'text',
                'value' => 'info@smkn4bogor.sch.id',
                'group' => 'contact',
                'description' => 'Alamat email resmi sekolah',
                'order' => 4,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 15,
                'key' => 'contact_website',
                'label' => 'Website',
                'type' => 'text',
                'value' => 'smkn4bogor.sch.id',
                'group' => 'contact',
                'description' => 'Alamat website resmi sekolah',
                'order' => 5,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 15:55:55',
            ],
            [
                'id' => 16,
                'key' => 'contact_map_embed',
                'label' => 'Embed Map',
                'type' => 'textarea',
                'value' => '<iframe src=\"https://maps.app.goo.gl/vGHtoRdcgShgX2ZU9\" width=\"100%\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>',
                'group' => 'contact',
                'description' => 'Kode embed Google Maps atau URL Google Maps. Untuk mendapatkan embed code: 1) Buka Google Maps 2) Cari lokasi 3) Klik \"Share\" 4) Pilih tab \"Embed a map\" 5) Salin kode iframe',
                'order' => 6,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 15:55:55',
            ],
            [
                'id' => 17,
                'key' => 'info_title',
                'label' => 'Judul Halaman Informasi',
                'type' => 'text',
                'value' => 'Informasi Terbaru',
                'group' => 'information',
                'description' => 'Judul halaman informasi',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 18,
                'key' => 'info_description',
                'label' => 'Deskripsi Halaman Informasi',
                'type' => 'textarea',
                'value' => 'Dapatkan informasi terbaru seputar kegiatan, pengumuman, dan berita dari SMKN 4 Bogor.',
                'group' => 'information',
                'description' => 'Deskripsi singkat halaman informasi',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 19,
                'key' => 'agenda_title',
                'label' => 'Judul Halaman Agenda',
                'type' => 'text',
                'value' => 'Agenda Kegiatan',
                'group' => 'agenda',
                'description' => 'Judul halaman agenda',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 20,
                'key' => 'agenda_description',
                'label' => 'Deskripsi Halaman Agenda',
                'type' => 'textarea',
                'value' => 'Jadwal dan agenda kegiatan terbaru SMKN 4 Bogor. Pantau terus jadwal kegiatan sekolah kami.',
                'group' => 'agenda',
                'description' => 'Deskripsi singkat halaman agenda',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 21,
                'key' => 'footer_about',
                'label' => 'Tentang Kami',
                'type' => 'editor',
                'value' => '<p>SMKN 4 Bogor adalah lembaga pendidikan kejuruan yang berkomitmen untuk menghasilkan lulusan yang kompeten dan berkarakter.</p>',
                'group' => 'footer',
                'description' => 'Teks tentang sekolah di footer',
                'order' => 1,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 22,
                'key' => 'footer_copyright',
                'label' => 'Teks Hak Cipta',
                'type' => 'text',
                'value' => '© 2025 SMKN 4 Bogor. All Rights Reserved.',
                'group' => 'footer',
                'description' => 'Teks hak cipta di footer',
                'order' => 2,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 23,
                'key' => 'social_facebook',
                'label' => 'Facebook',
                'type' => 'text',
                'value' => 'https://web.facebook.com/search/top?q=smk%20negeri%204%20bogor%20-%20nebrazka',
                'group' => 'footer',
                'description' => 'Link ke akun Facebook',
                'order' => 3,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 18:31:05',
            ],
            [
                'id' => 24,
                'key' => 'social_twitter',
                'label' => 'Twitter',
                'type' => 'text',
                'value' => 'https://twitter.com/smkn4bogor',
                'group' => 'footer',
                'description' => 'Link ke akun Twitter',
                'order' => 4,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-12 23:35:54',
            ],
            [
                'id' => 25,
                'key' => 'social_instagram',
                'label' => 'Instagram',
                'type' => 'text',
                'value' => 'https://instagram.com/smkn4bogor',
                'group' => 'footer',
                'description' => 'Link ke akun Instagram',
                'order' => 5,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 14:31:32',
            ],
            [
                'id' => 26,
                'key' => 'social_youtube',
                'label' => 'YouTube',
                'type' => 'text',
                'value' => 'https://youtube.com/@smknegeri4bogor905?si=fTyUWddpobkumWTr',
                'group' => 'footer',
                'description' => 'Link ke channel YouTube',
                'order' => 6,
                'created_at' => '2025-11-12 23:35:54',
                'updated_at' => '2025-11-14 18:31:05',
            ],
            [
                'id' => 27,
                'key' => 'expertise_title',
                'label' => 'Judul Program Keahlian',
                'type' => 'text',
                'value' => 'Program Keahlian',
                'group' => 'information',
                'description' => 'Judul bagian program keahlian',
                'order' => 3,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 28,
                'key' => 'expertise_1_name',
                'label' => 'Keahlian 1 - Nama',
                'type' => 'text',
                'value' => 'Rekayasa Perangkat Lunak',
                'group' => 'information',
                'description' => 'Nama program keahlian pertama',
                'order' => 4,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 14:31:32',
            ],
            [
                'id' => 29,
                'key' => 'expertise_1_description',
                'label' => 'Keahlian 1 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Mempelajari pembuatan aplikasi dan gim mulai dari perancangan hingga pengembangan.',
                'group' => 'information',
                'description' => 'Deskripsi program keahlian pertama',
                'order' => 5,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 30,
                'key' => 'expertise_2_name',
                'label' => 'Keahlian 2 - Nama',
                'type' => 'text',
                'value' => 'Teknik Jaringan Komputer dan Telekomunikasi',
                'group' => 'information',
                'description' => 'Nama program keahlian kedua',
                'order' => 6,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 31,
                'key' => 'expertise_2_description',
                'label' => 'Keahlian 2 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Fokus pada instalasi, konfigurasi, dan pemeliharaan jaringan komputer serta sistem telekomunikasi.',
                'group' => 'information',
                'description' => 'Deskripsi program keahlian kedua',
                'order' => 7,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 32,
                'key' => 'expertise_3_name',
                'label' => 'Keahlian 3 - Nama',
                'type' => 'text',
                'value' => 'Teknik Pengelasan dan Fabrikasi Logam',
                'group' => 'information',
                'description' => 'Nama program keahlian ketiga',
                'order' => 8,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 33,
                'key' => 'expertise_3_description',
                'label' => 'Keahlian 3 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Mempelajari teknik pengelasan dan pembuatan konstruksi logam sesuai standar industri.',
                'group' => 'information',
                'description' => 'Deskripsi program keahlian ketiga',
                'order' => 9,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 34,
                'key' => 'expertise_4_name',
                'label' => 'Keahlian 4 - Nama',
                'type' => 'text',
                'value' => 'Teknik Otomotif',
                'group' => 'information',
                'description' => 'Nama program keahlian keempat',
                'order' => 10,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 35,
                'key' => 'expertise_4_description',
                'label' => 'Keahlian 4 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Mendalami perawatan, perbaikan, dan sistem kerja kendaraan bermotor.',
                'group' => 'information',
                'description' => 'Deskripsi program keahlian keempat',
                'order' => 11,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 36,
                'key' => 'facilities_title',
                'label' => 'Judul Fasilitas Sekolah',
                'type' => 'text',
                'value' => 'Fasilitas Sekolah',
                'group' => 'information',
                'description' => 'Judul bagian fasilitas sekolah',
                'order' => 12,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 37,
                'key' => 'facility_1_title',
                'label' => 'Fasilitas 1 - Judul',
                'type' => 'text',
                'value' => 'Laboratorium Komputer PPLG',
                'group' => 'information',
                'description' => 'Judul fasilitas pertama',
                'order' => 13,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 38,
                'key' => 'facility_1_icon',
                'label' => 'Fasilitas 1 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-laptop',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk fasilitas pertama',
                'order' => 14,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 14:31:32',
            ],
            [
                'id' => 39,
                'key' => 'facility_1_description',
                'label' => 'Fasilitas 1 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Fasilitas praktik untuk kegiatan pemrograman, pengembangan aplikasi, dan pembuatan gim.',
                'group' => 'information',
                'description' => 'Deskripsi fasilitas pertama',
                'order' => 15,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 40,
                'key' => 'facility_2_title',
                'label' => 'Fasilitas 2 - Judul',
                'type' => 'text',
                'value' => 'Laboratorium TJKT',
                'group' => 'information',
                'description' => 'Judul fasilitas kedua',
                'order' => 16,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 41,
                'key' => 'facility_2_icon',
                'label' => 'Fasilitas 2 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-network-wired',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk fasilitas kedua',
                'order' => 17,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:35:18',
            ],
            [
                'id' => 42,
                'key' => 'facility_2_description',
                'label' => 'Fasilitas 2 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Laboratorium yang digunakan untuk praktik jaringan komputer, konfigurasi perangkat, dan sistem telekomunikasi.',
                'group' => 'information',
                'description' => 'Deskripsi fasilitas kedua',
                'order' => 18,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 43,
                'key' => 'facility_3_title',
                'label' => 'Fasilitas 3 - Judul',
                'type' => 'text',
                'value' => 'Bengkel TPFL',
                'group' => 'information',
                'description' => 'Judul fasilitas ketiga',
                'order' => 19,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 44,
                'key' => 'facility_3_icon',
                'label' => 'Fasilitas 3 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-tools',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk fasilitas ketiga',
                'order' => 20,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:35:18',
            ],
            [
                'id' => 45,
                'key' => 'facility_3_description',
                'label' => 'Fasilitas 3 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Ruang praktik pengelasan dan fabrikasi logam yang dilengkapi peralatan kerja standar industri.',
                'group' => 'information',
                'description' => 'Deskripsi fasilitas ketiga',
                'order' => 21,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 46,
                'key' => 'facility_4_title',
                'label' => 'Fasilitas 4 - Judul',
                'type' => 'text',
                'value' => 'Bengkel TO',
                'group' => 'information',
                'description' => 'Judul fasilitas keempat',
                'order' => 22,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 47,
                'key' => 'facility_4_icon',
                'label' => 'Fasilitas 4 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-car',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk fasilitas keempat',
                'order' => 23,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:35:18',
            ],
            [
                'id' => 48,
                'key' => 'facility_4_description',
                'label' => 'Fasilitas 4 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Bengkel otomotif untuk praktik perawatan, perbaikan, dan pemeriksaan sistem kendaraan bermotor.',
                'group' => 'information',
                'description' => 'Deskripsi fasilitas keempat',
                'order' => 24,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 49,
                'key' => 'facility_5_title',
                'label' => 'Fasilitas 5 - Judul',
                'type' => 'text',
                'value' => 'Kantin Sekolah',
                'group' => 'information',
                'description' => 'Judul fasilitas kelima',
                'order' => 25,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 50,
                'key' => 'facility_5_icon',
                'label' => 'Fasilitas 5 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-utensils',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk fasilitas kelima',
                'order' => 26,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 51,
                'key' => 'facility_5_description',
                'label' => 'Fasilitas 5 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Area penyedia makanan dan minuman bagi siswa dengan suasana yang bersih dan nyaman.',
                'group' => 'information',
                'description' => 'Deskripsi fasilitas kelima',
                'order' => 27,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 52,
                'key' => 'facility_6_title',
                'label' => 'Fasilitas 6 - Judul',
                'type' => 'text',
                'value' => 'Unit Kesehatan (UKS)',
                'group' => 'information',
                'description' => 'Judul fasilitas keenam',
                'order' => 28,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 53,
                'key' => 'facility_6_icon',
                'label' => 'Fasilitas 6 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-briefcase-medical',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk fasilitas keenam',
                'order' => 29,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:36:25',
            ],
            [
                'id' => 54,
                'key' => 'facility_6_description',
                'label' => 'Fasilitas 6 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Ruang layanan kesehatan untuk penanganan pertama dan pemantauan kondisi kesehatan siswa di sekolah.',
                'group' => 'information',
                'description' => 'Deskripsi fasilitas keenam',
                'order' => 30,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 55,
                'key' => 'achievements_title',
                'label' => 'Judul Prestasi Sekolah',
                'type' => 'text',
                'value' => 'Prestasi Sekolah',
                'group' => 'information',
                'description' => 'Judul bagian prestasi sekolah',
                'order' => 31,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 56,
                'key' => 'achievement_1_title',
                'label' => 'Prestasi 1 - Judul',
                'type' => 'text',
                'value' => 'Juara 2 TECHNOUPDATE X HIMPACT 2025',
                'group' => 'information',
                'description' => 'Judul prestasi pertama',
                'order' => 32,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 57,
                'key' => 'achievement_1_icon',
                'label' => 'Prestasi 1 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-trophy',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk prestasi pertama',
                'order' => 33,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 58,
                'key' => 'achievement_1_description',
                'label' => 'Prestasi 1 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Siswa SMKN 4 Bogor berhasil meraih Juara 2 dalam ajang TECHNOUPDATE X HIMPACT 2025, sebuah kompetisi inovasi dan teknologi yang menguji kreativitas, kemampuan analisis, serta keterampilan problem solving para peserta. Prestasi ini menjadi bukti kemampuan siswa dalam bersaing dan berinovasi di bidang teknologi.',
                'group' => 'information',
                'description' => 'Deskripsi prestasi pertama',
                'order' => 34,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 59,
                'key' => 'achievement_1_date',
                'label' => 'Prestasi 1 - Tanggal',
                'type' => 'text',
                'value' => '16 Oktober 2025',
                'group' => 'information',
                'description' => 'Tanggal prestasi pertama',
                'order' => 35,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 60,
                'key' => 'achievement_2_title',
                'label' => 'Prestasi 2 - Judul',
                'type' => 'text',
                'value' => 'Juara 3 Tim Voli Putra se-Bogor Raya',
                'group' => 'information',
                'description' => 'Judul prestasi kedua',
                'order' => 36,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 61,
                'key' => 'achievement_2_icon',
                'label' => 'Prestasi 2 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-trophy',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk prestasi kedua',
                'order' => 37,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:30:17',
            ],
            [
                'id' => 62,
                'key' => 'achievement_2_description',
                'label' => 'Prestasi 2 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Tim Voli Putra SMKN 4 Bogor berhasil meraih Juara 3 tingkat se-Bogor Raya, menunjukkan kekompakan, kerja keras, dan sportivitas tinggi dalam setiap pertandingan.',
                'group' => 'information',
                'description' => 'Deskripsi prestasi kedua',
                'order' => 38,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 63,
                'key' => 'achievement_2_date',
                'label' => 'Prestasi 2 - Tanggal',
                'type' => 'text',
                'value' => '27 Oktober 2023',
                'group' => 'information',
                'description' => 'Tanggal prestasi kedua',
                'order' => 39,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 64,
                'key' => 'achievement_3_title',
                'label' => 'Prestasi 3 - Judul',
                'type' => 'text',
                'value' => 'Juara 3 Bogor Inovation Award 2025',
                'group' => 'information',
                'description' => 'Judul prestasi ketiga',
                'order' => 40,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 65,
                'key' => 'achievement_3_icon',
                'label' => 'Prestasi 3 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-award',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk prestasi ketiga',
                'order' => 41,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 66,
                'key' => 'achievement_3_description',
                'label' => 'Prestasi 3 - Deskripsi',
                'type' => 'textarea',
                'value' => 'SMKN 4 Bogor meraih penghargaan pada Bogor Innovation Award 2025 sebagai bentuk apresiasi atas kreativitas dan inovasi yang dihasilkan dalam pengembangan solusi berbasis teknologi dan kebermanfaatan bagi masyarakat.',
                'group' => 'information',
                'description' => 'Deskripsi prestasi ketiga',
                'order' => 42,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 67,
                'key' => 'achievement_3_date',
                'label' => 'Prestasi 3 - Tanggal',
                'type' => 'text',
                'value' => '29 September 2025',
                'group' => 'information',
                'description' => 'Tanggal prestasi ketiga',
                'order' => 43,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 68,
                'key' => 'achievement_4_title',
                'label' => 'Prestasi 4 - Judul',
                'type' => 'text',
                'value' => 'Juara 1 The Ace 2025 UI/UX',
                'group' => 'information',
                'description' => 'Judul prestasi keempat',
                'order' => 44,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 69,
                'key' => 'achievement_4_icon',
                'label' => 'Prestasi 4 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-certificate',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk prestasi keempat',
                'order' => 45,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-13 03:35:13',
            ],
            [
                'id' => 70,
                'key' => 'achievement_4_description',
                'label' => 'Prestasi 4 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Siswa SMKN 4 Bogor berhasil meraih Juara 1 The Ace 2025 kategori UI/UX, melalui rancangan antarmuka yang inovatif, fungsional, dan berfokus pada pengalaman pengguna, membuktikan kompetensi unggul dalam bidang desain digital.',
                'group' => 'information',
                'description' => 'Deskripsi prestasi keempat',
                'order' => 46,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 71,
                'key' => 'achievement_4_date',
                'label' => 'Prestasi 4 - Tanggal',
                'type' => 'text',
                'value' => '29 September 2025',
                'group' => 'information',
                'description' => 'Tanggal prestasi keempat',
                'order' => 47,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 72,
                'key' => 'achievement_5_title',
                'label' => 'Prestasi 5 - Judul',
                'type' => 'text',
                'value' => 'Juara 2 Tim Pencak Silat di Kejuaran Pekan Olahraga Pelajar Daerah (POPDA Jabar)',
                'group' => 'information',
                'description' => 'Judul prestasi kelima',
                'order' => 48,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 73,
                'key' => 'achievement_5_icon',
                'label' => 'Prestasi 5 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-medal',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk prestasi kelima',
                'order' => 49,
                'created_at' => '2025-11-13 03:35:13',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 74,
                'key' => 'achievement_5_description',
                'label' => 'Prestasi 5 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Siswa SMKN 4 Bogor meraih Juara 2 Pencak Silat pada ajang Pekan Olahraga Pelajar Daerah (POPDA) Jawa Barat, menunjukkan kemampuan, ketekunan, dan sportivitas tinggi dalam seni bela diri tradisional.',
                'group' => 'information',
                'description' => 'Deskripsi prestasi kelima',
                'order' => 50,
                'created_at' => '2025-11-13 03:35:14',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 75,
                'key' => 'achievement_5_date',
                'label' => 'Prestasi 5 - Tanggal',
                'type' => 'text',
                'value' => '28 September 2025',
                'group' => 'information',
                'description' => 'Tanggal prestasi kelima',
                'order' => 51,
                'created_at' => '2025-11-13 03:35:14',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 76,
                'key' => 'achievement_6_title',
                'label' => 'Prestasi 6 - Judul',
                'type' => 'text',
                'value' => 'Juara 2 Tim Gulat di Kejuaran Pekan Olahraga Pelajar Daerah (POPDA Jabar)',
                'group' => 'information',
                'description' => 'Judul prestasi keenam',
                'order' => 52,
                'created_at' => '2025-11-13 03:35:14',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 77,
                'key' => 'achievement_6_icon',
                'label' => 'Prestasi 6 - Ikon',
                'type' => 'text',
                'value' => 'fas fa-medal',
                'group' => 'information',
                'description' => 'Ikon Font Awesome untuk prestasi keenam',
                'order' => 53,
                'created_at' => '2025-11-13 03:35:14',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 78,
                'key' => 'achievement_6_description',
                'label' => 'Prestasi 6 - Deskripsi',
                'type' => 'textarea',
                'value' => 'Tim Gulat SMKN 4 Bogor berhasil meraih Juara 2 pada Pekan Olahraga Pelajar Daerah (POPDA) Jawa Barat, sebagai bukti kekuatan, teknik, dan dedikasi tinggi dalam cabang olahraga gulat.',
                'group' => 'information',
                'description' => 'Deskripsi prestasi keenam',
                'order' => 54,
                'created_at' => '2025-11-13 03:35:14',
                'updated_at' => '2025-11-14 15:24:10',
            ],
            [
                'id' => 79,
                'key' => 'achievement_6_date',
                'label' => 'Prestasi 6 - Tanggal',
                'type' => 'text',
                'value' => '28 September 2025',
                'group' => 'information',
                'description' => 'Tanggal prestasi keenam',
                'order' => 55,
                'created_at' => '2025-11-13 03:35:14',
                'updated_at' => '2025-11-14 15:30:17',
            ],
        ];
        DB::table('site_settings')->insert($data);


        // Seeding table: user_likes
        DB::table('user_likes')->truncate();
        $data = [
            [
                'id' => 12,
                'user_id' => 6,
                'foto_id' => 2,
                'created_at' => '2025-11-15 01:00:04',
                'updated_at' => '2025-11-15 01:00:04',
            ],
        ];
        DB::table('user_likes')->insert($data);


        // Seeding table: user_dislikes
        DB::table('user_dislikes')->truncate();
        $data = [
            [
                'id' => 3,
                'user_id' => 6,
                'foto_id' => 1,
                'created_at' => '2025-11-15 01:00:01',
                'updated_at' => '2025-11-15 01:00:01',
            ],
        ];
        DB::table('user_dislikes')->insert($data);


        // Seeding table: gallery_like_logs
        DB::table('gallery_like_logs')->truncate();
        $data = [
            [
                'id' => 1,
                'user_id' => 6,
                'foto_id' => 1,
                'action' => 'dislike',
                'created_at' => '2025-11-15 01:00:01',
                'updated_at' => '2025-11-15 01:00:01',
            ],
            [
                'id' => 2,
                'user_id' => 6,
                'foto_id' => 2,
                'action' => 'like',
                'created_at' => '2025-11-15 01:00:04',
                'updated_at' => '2025-11-15 01:00:04',
            ],
        ];
        DB::table('gallery_like_logs')->insert($data);

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
